//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscolaContext : DbContext
    {
        public EscolaContext()
            : base("name=EscolaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prova> Provas { get; set; }
        public virtual DbSet<ProvaAluno> ProvaAlunoes { get; set; }
        public virtual DbSet<Questao> Questaos { get; set; }
        public virtual DbSet<QuestaoAlternativa> QuestaoAlternativas { get; set; }
        public virtual DbSet<RespostaQuestaoAluno> RespostaQuestaoAlunoes { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<Turma> Turmas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
