//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prova
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prova()
        {
            this.ProvaAlunoes = new HashSet<ProvaAluno>();
            this.Questaos = new HashSet<Questao>();
        }
    
        public int ProvaID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> TurmaID { get; set; }
    
        public virtual Turma Turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvaAluno> ProvaAlunoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questao> Questaos { get; set; }
    }
}
