//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvaAluno
    {
        public int ProvaAlunoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> ProvaID { get; set; }
        public Nullable<double> Nota { get; set; }
    
        public virtual Prova Prova { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
