//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoAlternativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestaoAlternativa()
        {
            this.RespostaQuestaoAlunoes = new HashSet<RespostaQuestaoAluno>();
        }
    
        public int QuestaoAlternativaID { get; set; }
        public Nullable<int> QuestaoID { get; set; }
        public string Resposta { get; set; }
        public Nullable<bool> Correta { get; set; }
    
        public virtual Questao Questao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaQuestaoAluno> RespostaQuestaoAlunoes { get; set; }
    }
}
