//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questao()
        {
            this.QuestaoAlternativas = new HashSet<QuestaoAlternativa>();
            this.RespostaQuestaoAlunoes = new HashSet<RespostaQuestaoAluno>();
        }
    
        public int QuestaoID { get; set; }
        public Nullable<int> ProvaID { get; set; }
        public string Enunciado { get; set; }
    
        public virtual Prova Prova { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestaoAlternativa> QuestaoAlternativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaQuestaoAluno> RespostaQuestaoAlunoes { get; set; }
    }
}
