//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegradorUlifeParaDevs.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaQuestaoAluno
    {
        public int RespostaQuestaoAlunoID { get; set; }
        public Nullable<int> QuestaoID { get; set; }
        public Nullable<int> QuestaoAlternativaID { get; set; }
    
        public virtual Questao Questao { get; set; }
        public virtual QuestaoAlternativa QuestaoAlternativa { get; set; }
    }
}
